// Login
export const USER_LOGIN = 'USER_LOGIN'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'
export const FETCH_SESSION = 'FETCH_SESSION'

// Record
export const OPEN_DETAIL = 'OPEN_DETAIL'
export const FETCH_RECORDS = 'FETCH_RECORDS'
export const FETCH_RECORD = 'FETCH_RECORD'

// Recommend
export const FETCH_RECOMMENDS = 'FETCH_RECOMMENDS'
export const FETCH_RECOMMEND = 'FETCH_RECOMMEND'

// Together
export const FETCH_TOGETHERS = 'FETCH_TOGETHERS'
export const FETCH_TOGETHER = 'FETCH_TOGETHER'

// Comment
export const FETCH_RECOMMEND_COMMENTS = 'FETCH_RECOMMEND_COMMENTS'
export const FETCH_RECOMMEND_COMMENT = 'FETCH_RECOMMEND_COMMENT'
export const FETCH_TOGETHER_COMMENTS = 'FETCH_TOGETHER_COMMENTS'
export const FETCH_TOGETHER_COMMENT = 'FETCH_TOGETHER_COMMENT'

