// 크롤링
export const CRAWL_START = 'CRAWL_START'
export const CRAWL_ADDRESS = 'CRAWL_ADDRESS'

export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

export const FETCH_LOGIN = 'FETCH_LOGIN'
export const FETCH_SESSION = 'FETCH_SESSION'
export const FETCH_MEMBER = 'FETCH_MEMBER'

