
export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'

export const FETCH_REVIEW_LIST = 'FETCH_REVIEW_LIST'
export const FETCH_REVIEW = 'FETCH_REVIEW'

export const CRAWL_START = 'CRAWL_START'

